# Generated by Django 3.2.9 on 2021-11-18 17:46

from django.db import migrations


def forward_code(apps, se):
    SomeModel = apps.get_model('someapp', 'SomeModel')
    alias = se.connection.alias
    SomeModel.objects.using(alias).bulk_create([
        SomeModel(value='value1'),
        SomeModel(value='value2')
    ])


def reverse_code(apps, se):
    SomeModel = apps.get_model('someapp', 'SomeModel')
    alias = se.connection.alias
    SomeModel.objects.using(alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=forward_code, reverse_code=reverse_code)
    ]
