# Generated by Django 3.2.9 on 2021-11-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0003_auto_20211123_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='somemodel',
            name='other1',
            field=models.ManyToManyField(related_name='other1', to='someapp.SomeOtherModel'),
        ),
    ]
