# Generated by Django 3.2.9 on 2021-11-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('someapp', '0004_somemodel_other1'),
    ]

    operations = [
        migrations.AddField(
            model_name='somemodel',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AlterField(
            model_name='somemodel',
            name='other1',
            field=models.ManyToManyField(related_name='others', to='someapp.SomeOtherModel'),
        ),
    ]
